### ISSUE TITLE
Loosen dependency on resque-logger

### ISSUE THREAD

**Issue by tf** [codevise/state_machine_job#1]
The logging functionality depends on the resque-logger gem and `perform` fails if it is not configured correctly. Maybe this dependency could be optional or the logger could be configurable.

**Comment by tf** [comment]
When migrating to ActiveJob (#7), we should consider simply using ActiveJob's default behavior of logging into `logs/production.rb` prefixed with a tag. This way the `resque-logger` dependency can be dropped completely.

**Comment by tilsammans** [comment]
@tf any timeline on these issues getting fixed?

The disappearance of fatal errors into a log file on a single server is really becoming very problematic for us. They should just bubble up so that our exception tracker can notify us. As it stands now, we have to wait for users to complain, which is far too late.

**Comment by tf** [comment]
Are you running version 1.0 of this gem? Since #5, exceptions should simply bubble up. There is some custom resque setup required to [integrate with exception notification](https://github.com/smartinez87/exception_notification/blob/c0681f578f0a2499c1eac1537a0a2ea419be20c2/lib/generators/exception_notification/templates/exception_notification.rb#L6).

**Comment by tilsammans** [comment]
I am running 1.0.0, but did not do any integration. (Spoiled as I am with Sidekiq) And exceptions in Resque are not being passed on.

Since we track exceptions using Sentry, I'll give [resque-sentry](https://github.com/gocardless/resque-sentry) a shot!

**Comment by tf** [comment]
Once we have moved to ActiveJob, Resque should merely be the default choice made by the generator, rigth? I'd expect it to be straightforward to swap in Sidekiq then.

**Comment by tilsammans** [comment]
Such is the theory, yes. :)
