### ISSUE TITLE
Add resque-retry as a dependency?

### ISSUE THREAD

**Issue by tilsammans** [codevise/state_machine_job#8]
It gives Sidekiq-like retry and exponential backoff.

https://github.com/lantins/resque-retry

**Comment by tf** [comment]
For its next major version I'd like to migrate Pageflow's jobs to ActiveJob. This would also require a new major version of this gem, making it Resque-agnostic. If I see it correctly, ActiveJob [already contains](http://api.rubyonrails.org/classes/ActiveJob/Exceptions/ClassMethods.html#method-i-retry_on) retry functionality. We'd also get some other nice ActiveJob features like `rescue_from`.

**Comment by tilsammans** [comment]
Oh, that's even better. For better or worse, ActiveJob is the future.

Cool. What is the timeline for this version? It would be 13.0.0, correct? I have some other requests for that release too. A websocket instead of the poll inside the editor, for instance. ;)

**Comment by tf** [comment]
No concrete timeline so far. Yes, Rails 5 and websocket based edit locks should be our goal. I'd also put Webpacker 3.0 in host applications on my wishlist. That would mean a `pageflow` npm package, which in turn would be a first step towards JS only page type plugins.
